### ISSUE TITLE
GX Agent fails to start due to SSL errors

### ISSUE THREAD

**Issue by jstaffans-relex** [great-expectations/cloud#228]
I wanted to try the public beta out, following instructions from https://docs.greatexpectations.io/docs/cloud/deploy_gx_agent and deploying the agent self-hosted using Docker. However, the agent fails to start:

```
GX Agent version: 20240424.0
Initializing the GX Agent.
Loading a DataContext - this might take a moment.
DataContext is ready.
Opening connection to GX Cloud.
The GX Agent is ready.
[ERROR] pika.adapters.utils.io_services_utils: SSL do_handshake failed: error=SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'); <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.2', 40378), raddr=('35.153.235.234', 5671)>
Traceback (most recent call last):
  File "/tmp/pypoetry/virtualenvs/great-expectations-cloud-9TtSrW0h-py3.10/lib/python3.10/site-packages/pika/adapters/utils/io_services_utils.py", line 636, in _do_ssl_handshake
    self._sock.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)
[ERROR] pika.adapters.utils.connection_workflow: Attempt to create the streaming transport failed: SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)'); 'mq.greatexpectations.io'/(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('35.153.235.234', 5671)); ssl=True
[ERROR] pika.adapters.utils.connection_workflow: AMQPConnector - reporting failure: AMQPConnectorTransportSetupError: SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')
```

This is on macos.

**Comment by rachhouse** [comment]
Hi @jstaffans-relex, thanks for reaching out! We're glad you're interested to try out GX Cloud.

Based on your error, this looks like a possible firewall issue. Can you please verify that you're not blocked from reaching the following URI/port?
* URI: [mq.greaatexpectations.io](http://mq.greaatexpectations.io/)
* Port: 5671
* TLS: Yes

If you are trying to run the GX Agent on your work machine and currently have an IT team or resource available, you can have them check if it's blocked, or you can also test your connection directly using `nmap mq.greatexpectations.io -p 5671`.

**Comment by jstaffans-relex** [comment]
Indeed the issue was with firewall, thanks!

**Comment by rachhouse** [comment]
Hi @jstaffans-relex, thanks for confirming that was the issue!

I also wanted to add that if you run into any further errors with the GX Agent or GX Cloud as you try out the product, please reach out to us using support@greatexpectations.io. This email will create a helpdesk ticket in our support portal. It was an oversight that GitHub issues were enabled on this repo, our goal is to consolidate & streamline support for GX Cloud issues within our support portal.

And, if you have general questions about using GX (Cloud or OSS), I'd recommend our Discourse forums: https://discourse.greatexpectations.io/
